name: build images

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "*" ]

permissions:
  contents: read
  packages: write

jobs:
  app-server:
    if: "!contains(github.event.commits[0].message, 'skip:app-server')"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: build server image
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        context: ./app/server
        push: true
        tags: ghcr.io/rckik-lublin/app:server
